name: Train & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train_build_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Train models (skip MLflow model logging in CI)
      - name: Train models
        env:
          GITHUB_ACTIONS: "true"   # ✅ Tells train_multiple.py we are in CI
        run: |
          python run_experiment.py

      # Step 5: Verify artifacts folder
      - name: Verify artifact
        run: ls -la artifacts

      # Step 6: Deploy to Hugging Face Space
      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://GokulV:$HF_TOKEN@huggingface.co/spaces/GokulV/Mobile_price_prediction.git hf_space
          cp app.py hf_space/
          cp requirements.txt hf_space/
          mkdir -p hf_space/artifacts
          cp artifacts/best_model.pkl hf_space/artifacts/
          cd hf_space
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add -A
          git commit -m "🚀 Deploy model update from commit $GITHUB_SHA" || echo "No changes"
          git push origin main
